# Generated by Django 5.0.6 on 2024-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='semester',
            field=models.CharField(blank=True, choices=[('s1', 'Semester 1'), ('s2', 'Semester 2'), ('s3', 'Semester 3'), ('s4', 'Semester 4'), ('s5', 'Semester 5'), ('s6', 'Semester 6'), ('s7', 'Semester 7'), ('s8', 'Semester 8')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
